name: YouTube API Test

on:
  workflow_dispatch: # 手動実行できるようにする

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests

      - name: Call YouTube API
        run: |
          python - << 'EOF'
          import os, requests

          api_key = os.environ["YOUTUBE_API_KEY"]
          url = f"https://www.googleapis.com/youtube/v3/search?part=snippet&q=cat&type=video&maxResults=1&key={api_key}"
          r = requests.get(url)
          print("Status:", r.status_code)
          print("Result:", r.json())
          EOF
        env:
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
